service: tickets-cron-job

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: tickets-cron-job-dev-deployment-bucket
    serverSideEncryption: AES256 
    blockPublicAccess: true
  environment:
    STAGE: ${self:provider.stage}
    
  

functions:
  ticketsJob:
    handler: src/tickets/infrastructure/bootstrap/lambda-entry.handler
    memorySize: 256
    timeout: 15
    logRetentionInDays: 1
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: true

plugins:
  - serverless-esbuild
  # - serverless-offline

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: 
      - '@nestjs/microservices'
      - '@nestjs/websockets'
      - 'class-validator'
      - 'class-transformer'
      - 'aws-sdk'
    target: node18
    platform: node
    concurrency: 10
    inject:
      - ./crypto-polyfill.js