service: tickets-cron-job

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  architecture: arm64
  environment:
    NODE_ENV: production

functions:
  syncTickets:
    handler: dist/tickets/application/service/TicketsSchedulerService.handleCron
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: true

plugins:
  - serverless-esbuild

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node18
    platform: node
    concurrency: 10
